const GH = 'https://github.com/TejasRamanujam';

export const CASE_STUDIES = {
  'working-drawing': {
    sheet: '03·A',
    title: 'The Working Drawing',
    problem: 'A conventional portfolio would flatten the work into a list of links. This site instead makes the interface itself a working software sample while keeping the résumé facts and projects fast to scan.',
    architecture: ['React sheet', 'Canvas plotter', 'Static deploy'],
    decisions: [
      'Use Canvas 2D for an accumulating flow-field drawing without adding a rendering library.',
      'Keep project and résumé facts in plain data modules so presentation stays separate from content.',
      'Treat reduced motion, keyboard access, and direct-linkable sheets as core behavior.',
      'Ship as a static Vite build for a small, cacheable deployment surface.',
    ],
    stack: ['React', 'Vite', 'Canvas 2D', 'Variable Fonts'],
    live: 'https://tejasramanujam.vercel.app',
    repo: `${GH}/portfolio`,
  },
  connection: {
    sheet: '03·B',
    title: 'Connection — AI Voice Assistant',
    problem: 'Voice interfaces often fail when speech APIs or permissions are unavailable. Connection keeps the same assistant usable through a text fallback while coordinating Gemini reasoning, tool calls, live transcripts, and spoken responses.',
    architecture: ['Speech / text', 'Next.js agent', 'Gemini + tools', 'Voice response'],
    decisions: [
      'Use the Web Speech API where supported and preserve text input everywhere.',
      'Expose interim recognition results so the user can see what the system is hearing.',
      'Run web search, to-do, calendar, and clock operations through an agentic tool loop.',
      'Keep the build testable without environment secrets; only live reasoning needs a key.',
    ],
    stack: ['Next.js 14', 'TypeScript', 'Gemini', 'Prisma', 'Jest'],
    live: 'https://connection-assistant.vercel.app',
    repo: `${GH}/Connection-Voice-Assistant`,
  },
  neuron: {
    sheet: '03·C',
    title: 'Neuron — Project Database',
    problem: 'A growing set of CS build plans needs more structure than a document or link list. Neuron makes the catalogue searchable by text, difficulty, and taxonomy while keeping complete build plans available behind a REST API.',
    architecture: ['React + TS', 'FastAPI', 'SQLAlchemy', 'Neon Postgres'],
    decisions: [
      'Separate the Vite client from FastAPI serverless functions at the API boundary.',
      'Model difficulty and taxonomy as filters rather than burying them in prose.',
      'Keep navigation keyboard-first for fast catalogue scanning.',
      'Use SQLAlchemy over Neon Postgres for a clear persistence layer.',
    ],
    stack: ['React', 'TypeScript', 'FastAPI', 'SQLAlchemy', 'Neon'],
    live: 'https://neuron-database.vercel.app',
    repo: `${GH}/Neuron-Project-Database`,
  },
  neurosurge: {
    sheet: '03·D',
    title: 'Neurosurge — Second Brain',
    problem: 'Notes lose context when they live only in folders. Neurosurge turns wikilinks and hashtags into a navigable knowledge graph, then adds rehearsal and semantic retrieval so the same notes can be explored and remembered.',
    architecture: ['Notes + imports', 'FastAPI', 'Neon + pgvector', 'Graph / search'],
    decisions: [
      'Derive graph relationships from familiar wikilinks instead of a separate linking workflow.',
      'Use pgvector and Gemini embeddings for semantic retrieval alongside explicit links.',
      'Pair exploration with spaced-repetition flashcards rather than treating notes as passive storage.',
      'Support PDF and DOCX import while keeping the interface responsive to phone widths.',
    ],
    stack: ['React', 'TypeScript', 'FastAPI', 'Neon', 'pgvector', 'Gemini'],
    live: 'https://neurosurge.vercel.app',
    repo: `${GH}/Neurosurge-Second-Brain`,
  },
  scribbly: {
    sheet: '03·E',
    title: 'Scribbly — Collaborative Whiteboard',
    problem: 'Collaborative drawing needs immediate feedback without sacrificing durable history. Scribbly broadcasts live strokes, stores them as an event log, and can replay the drawing timeline after reconnects or refreshes.',
    architecture: ['Canvas clients', 'Liveblocks', 'FastAPI', 'Neon event log'],
    decisions: [
      'Use Liveblocks for realtime presence with a polling fallback.',
      'Persist a stroke event log so realtime transport is never the source of truth.',
      'Reconcile events by stroke id to prevent duplicate application across transports.',
      'Retain per-user undo and redo while supporting touch input and SVG/PNG export.',
    ],
    stack: ['React', 'TypeScript', 'FastAPI', 'Liveblocks', 'Neon'],
    live: 'https://scribbly-collab.vercel.app',
    repo: `${GH}/Scribbly-Collaborative-Whiteboard`,
  },
};
